name: "Setup Dependencies ðŸ› ï¸"
description: "Setup Node.js, install dependencies, and configure environment"
runs:
  using: "composite"
  steps:
    - name: Check out the repository code
      uses: actions/checkout@v4
    - name: Setup node and cache yarn
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: yarn
    - name: Install dependencies
      run: yarn
      shell: bash
    - name: Install mock server dependencies
      run: cd mock-server && yarn && cd ..
      shell: bash
    - name: Create the env file
      run: echo "${{ inputs.env_vars }}" > .env
      shell: bash

inputs:
  env_vars:
    description: "Environment variables"
    required: true
