name: "Setup Dependencies ðŸ› ï¸"
description: "Setup Node.js, install dependencies, and configure environment"
runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash
    - name: Setup node and cache pnpm
      uses: actions/setup-node@v4
      with:
        node-version: 24.13.1
        cache: pnpm
    - name: Install dependencies
      run: pnpm install
      shell: bash
    - name: Create the env file
      run: echo "${{ inputs.env_var }}" > .env
      shell: bash

inputs:
  env_var:
    description: "Environment variable"
    required: true
