compressionLevel: mixed

enableGlobalCache: false
# Node modules are needed for the current Podfile to work, specifically lines 1-6 in the Podfile about resolving react_native_pods.rb
nodeLinker: node-modules
